export default {
  PROFILE: 'PROFILE',
  SUBADMIN: 'SUBADMIN',
  REPORTS: 'REPORTS',
  REPORT_TYPES: 'REPORT_TYPES',
  REPORT_TYPE_DETAIL: 'REPORT_TYPE_DETAIL',
  USERS: 'USERS',
  CATEGORIES: 'CATEGORIES',
  CATEGORY_DETAIL: 'CATEGORY_DETAIL',
  POSTS: 'POSTS',
};
